export class DoctorProfiles {
  id: number;
  userId: number;
  regNo: string;
  validity: any;
  sex: string;
  picUrl: string;
  age: number;
  address: string;
  speciality: any;
  experience: number;
  description: string;
  videoUrl: string;
  appearUrl: string;
  waitingTime: number;
  ratingValue: number;
  ratingCount: number;
  shortBio: string;
  longBio: string;
  Qualification: any ;
  qualificationStr: string;
  Language: any;
  languageStr: string;
  ConsultationMode: any;
  consultationModeStr: Object;
  Location: any;
  locationStr: string;
  status: string;
  createdAt: any;
  createdBy: number;
  updatedAt: any;
  updatedBy: number;
  lastupdated: string;
  termsAccepted: boolean;
}
